CREATE USER ms_usr WITH PASSWORD 'ms_usr_password';
CREATE SCHEMA IF NOT EXISTS auth;
GRANT CONNECT ON DATABASE "db-auth" TO ms_usr;
GRANT USAGE ON SCHEMA auth TO ms_usr;
ALTER USER ms_usr SET search_path TO auth, public;
ALTER USER postgres SET search_path TO auth, public;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ms_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth
    GRANT USAGE, SELECT ON SEQUENCES TO ms_usr;
