changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5434/db-account?currentSchema=account
username=postgres
password=postgres
driver=org.postgresql.Driver
classpath=/liquibase/lib/postgresql.jar
logLevel=INFO
