CREATE USER ms_usr WITH PASSWORD 'ms_usr_password';
CREATE SCHEMA IF NOT EXISTS game;
GRANT CONNECT ON DATABASE "db-game" TO ms_usr;
GRANT USAGE ON SCHEMA game TO ms_usr;
ALTER USER ms_usr SET search_path TO game, public;
ALTER USER postgres SET search_path TO game, public;
ALTER DEFAULT PRIVILEGES IN SCHEMA game
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ms_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA game
    GRANT USAGE, SELECT ON SEQUENCES TO ms_usr;
